---
name: Compile Firmwares

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main
  

jobs:
  compile_playground_sketch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Compile demo sketch on ESP32
        uses: arduino/compile-sketches@v1
        with:
          sketch-paths: |
            - ./iot-playground.ino
          libraries: |
            - 
          enable-deltas-report: true
          enable-warnings-report: true
          sketches-report-path: ${{ env.SKETCHES_REPORTS_PATH }}
        
      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          path: iot-playground.ino.bin
          name: iot-playground
          compression-level: 0
          # if-no-files-found: error
  
  compile_vizard_sketch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Compile vizard sketch on ESP32
        uses: arduino/compile-sketches@v1
        with:
          # platforms: | 
          #   - name: esp32:esp32
          #     source-url: https://dl.espressif.com/dl/package_esp32_index.json
          #     version: 1.0.6
          # fqbn: esp32:esp32:m5stack-core-esp32
          sketch-paths: |
            - ./vizard/vizard.ino
          libraries: |
            - 
          enable-deltas-report: true
          enable-warnings-report: true
          sketches-report-path: ${{ env.SKETCHES_REPORTS_PATH }}
        
      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          path: vizard/vizard.ino.bin
          name: vizard
          compression-level: 0
          # if-no-files-found: error

  compile_one_button_sketch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install platform
        run: |
          set -x
          # arduino-cli core install esp32:esp32
          arduino-cli core install m5stack:esp32 --additional-urls "file:///${PWD}/package_m5stack_index.json"

          arduino-cli core search m5stack
          arduino-cli board listall

          arduino-cli lib install M5StickCPlus2 --log-level warn --verbose
          
      - name: Install esptool
        run: |
          set -x
          pip install -U esptool

      - name: Compile M5Cardputer Sketch
        run: |
          arduino-cli compile --fqbn m5stack:esp32:m5stack_stickc_plus2 -e \
                              --build-property build.partitions=huge_app \
                              --build-property upload.maximum_size=3145728 \
                              --libraries M5StickCPlus2 \
                              ./M5StickCPlus2/EXamples/OneButton-main/OneButton/OneButton.ino
      
      - name: List all files
        if: always()
        continue-on-error: true
        run: |
          set -x -e
          pwd
          tree
      
      - name: Create firmware
        run: |
          set -x

          esptool.py --chip esp32s3 merge_bin --output OneButton.m5stack_stickc_plus2.bin \
            0x0000 M5StickCPlus2/EXamples/OneButton-main/OneButton/build/m5stack.esp32.m5stack_stickc_plus2/OneButton.ino.bootloader.bin \
            0x8000 M5StickCPlus2/EXamples/OneButton-main/OneButton/build/m5stack.esp32.m5stack_stickc_plus2/OneButton.ino.partitions.bin \
            0x10000 M5StickCPlus2/EXamples/OneButton-main/OneButton/build/m5stack.esp32.m5stack_stickc_plus2/OneButton.ino.bin

        
      - name: Upload OneButton firmware
        uses: actions/upload-artifact@v4
        with:
          path: OneButton.m5stack_stickc_plus2.bin
          name: OneButton
          compression-level: 0
          # if-no-files-found: error

