---
name: Demo Compile with ESP IDF

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "v*"
    # paths:
    #   - demo_esp_idf/**
  pull_request:
    branches:
      - main
    # paths:
    #   - demo_esp_idf/**

jobs:

  compile_demo_idf:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: demo_esp_idf

    steps:
      - uses: actions/checkout@v4

      - name: List all files
        if: always()
        continue-on-error: true
        run: |
          set -x
          pwd
          ls -all
          tree
      
      - name: Build using esp-idf
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v4.4.6
          target: esp32s3

      - name: Merge Firmware Binary
        run: |
          . $HOME/esp/esp-idf/export.sh
          cd build
          esptool.py merge_bin -o Demo.IDF.bin --fill-flash-size 4MB @flash_args

      - name: List all files
        if: always()
        continue-on-error: true
        run: |
          set -x
          pwd
          ls -all
          tree
        
      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          path: Demo.IDF.bin
          name: Demo.IDF
          compression-level: 0
          if-no-files-found: error
